import type { TemplateDefinition } from './types';

export const VIDEO_TEMPLATES: TemplateDefinition[] = [
    {
        id: 'corporate-reveal',
        name: 'Corporate Reveal',
        category: 'corporate',
        description: 'Logo fades in with gold shimmer. Subtitle slides up cleanly.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['business', 'professional', 'logo'],
        accent: '#f59e0b',
        thumbnailGradient: ['#1e293b', '#0f172a'],
        thumbnailEmoji: '🏢',
        defaultText: { title: 'YOUR BRAND', subtitle: 'Excellence Redefined' },
        defaultColors: { primary: '#f59e0b', bg: '#0f172a', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'linear', colors: ['#1e293b', '#0f172a'], angle: 135 } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Vignette', type: 'overlay', config: { type: 'vignette', intensity: 0.6 }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Gold Line', type: 'shape', config: { shape: 'rect', fill: '#f59e0b', width: 80, height: 3 }, x: 880, y: 510, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 8, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], scaleX: [{ time: 1, value: 0, easing: 'spring' }, { time: 2.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'YOUR BRAND', fontFamily: 'Inter', fontSize: 72, fontWeight: '800', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 12, glowColor: '#f59e0b', glowRadius: 20 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], scaleX: [{ time: 0.5, value: 0.8, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }], scaleY: [{ time: 0.5, value: 0.8, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Excellence Redefined', fontFamily: 'Inter', fontSize: 24, fontWeight: '300', fill: '#94a3b8', textAlign: 'center', letterSpacing: 4 }, x: 960, y: 560, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }], y: [{ time: 1.5, value: 590, easing: 'spring' }, { time: 3, value: 560, easing: 'spring' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'neon-cyber',
        name: 'Neon Cyber',
        category: 'trendy',
        description: 'Dark background with cyan/purple neon glow and scanlines.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['tech', 'neon', 'cyber', 'gaming'],
        accent: '#06b6d4',
        thumbnailGradient: ['#0a0a1a', '#1a0a2e'],
        thumbnailEmoji: '⚡',
        defaultText: { title: 'CYBER TECH', subtitle: 'Next Generation' },
        defaultColors: { primary: '#06b6d4', secondary: '#a855f7', bg: '#030718', text: '#e2e8f0' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'radial', colors: ['#0d0d1f', '#030718'] } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Scanlines', type: 'overlay', config: { type: 'scanlines' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Particles', type: 'particle', config: { count: 60, color: ['#06b6d4', '#a855f7', '#818cf8'], size: 2, speed: 1.5, spread: 400, lifetime: 3, shape: 'dot', gravity: -0.05, emitterX: 960, emitterY: 540 }, x: 0, y: 0, opacity: 0.8, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'CYBER TECH', fontFamily: 'Inter', fontSize: 80, fontWeight: '900', fill: '#06b6d4', textAlign: 'center', uppercase: true, glowColor: '#06b6d4', glowRadius: 40, stroke: '#a855f7', strokeWidth: 1 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.3, endTime: 8, keyframes: { opacity: [{ time: 0.3, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Next Generation', fontFamily: 'Inter', fontSize: 22, fontWeight: '400', fill: '#a855f7', textAlign: 'center', glowColor: '#a855f7', glowRadius: 15, letterSpacing: 8 }, x: 960, y: 570, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 8, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeOut' }, { time: 2.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'luxury-serif',
        name: 'Luxury Serif',
        category: 'corporate',
        description: 'Cream and black editorial luxury feel with horizontal wipe.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['luxury', 'fashion', 'editorial', 'premium'],
        accent: '#d4a853',
        thumbnailGradient: ['#1a1208', '#2d1f0a'],
        thumbnailEmoji: '💎',
        defaultText: { title: 'MAISON', subtitle: 'Luxury Redefined Since 1920' },
        defaultColors: { primary: '#d4a853', bg: '#0a0804', text: '#f5f0e8' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#0a0804' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Gold Bar Left', type: 'shape', config: { shape: 'rect', fill: '#d4a853', width: 3, height: 120 }, x: 340, y: 420, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }], scaleY: [{ time: 0.5, value: 0, easing: 'spring' }, { time: 1.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Gold Bar Right', type: 'shape', config: { shape: 'rect', fill: '#d4a853', width: 3, height: 120 }, x: 1580, y: 420, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }], scaleY: [{ time: 0.5, value: 0, easing: 'spring' }, { time: 1.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'MAISON', fontFamily: 'Playfair Display', fontSize: 110, fontWeight: '700', fill: '#f5f0e8', textAlign: 'center', letterSpacing: 24 }, x: 960, y: 470, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.2, endTime: 8, keyframes: { opacity: [{ time: 0.2, value: 0, easing: 'easeInOut' }, { time: 2, value: 1, easing: 'easeInOut' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Luxury Redefined Since 1920', fontFamily: 'Inter', fontSize: 18, fontWeight: '300', fill: '#d4a853', textAlign: 'center', letterSpacing: 6 }, x: 960, y: 570, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'particle-burst',
        name: 'Particle Burst',
        category: 'trendy',
        description: 'Text assembled from animated GPU particles on a dark canvas.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['energy', 'particles', 'dynamic', 'impact'],
        accent: '#f97316',
        thumbnailGradient: ['#18090a', '#0a0505'],
        thumbnailEmoji: '✨',
        defaultText: { title: 'IGNITE', subtitle: 'The Future is Now' },
        defaultColors: { primary: '#f97316', secondary: '#ef4444', bg: '#0a0505', text: '#fff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#080505' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Particles', type: 'particle', config: { count: 120, color: ['#f97316', '#ef4444', '#fbbf24', '#fff'], size: 3, speed: 3, spread: 600, lifetime: 2.5, shape: 'spark', gravity: 0.1, emitterX: 960, emitterY: 500 }, x: 0, y: 0, opacity: 0.9, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: { opacity: [{ time: 0, value: 0, easing: 'easeOut' }, { time: 1, value: 0.9, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'IGNITE', fontFamily: 'Inter', fontSize: 120, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, glowColor: '#f97316', glowRadius: 50 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.8, endTime: 8, keyframes: { opacity: [{ time: 0.8, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], scaleX: [{ time: 0.8, value: 0.5, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }], scaleY: [{ time: 0.8, value: 0.5, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'The Future is Now', fontFamily: 'Inter', fontSize: 24, fontWeight: '400', fill: '#f97316', textAlign: 'center', letterSpacing: 5 }, x: 960, y: 580, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 2, endTime: 8, keyframes: { opacity: [{ time: 2, value: 0, easing: 'easeOut' }, { time: 3.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'social-story',
        name: 'Social Story',
        category: 'social',
        description: 'Vertical 9:16 bold color blocks for Instagram/TikTok stories.',
        aspectRatio: '9:16',
        duration: 6,
        tags: ['instagram', 'tiktok', 'story', 'vertical', 'social'],
        accent: '#ec4899',
        thumbnailGradient: ['#831843', '#1e1b4b'],
        thumbnailEmoji: '📱',
        defaultText: { title: 'BIG NEWS', subtitle: 'Tap to learn more', cta: 'SHOP NOW' },
        defaultColors: { primary: '#ec4899', secondary: '#8b5cf6', bg: '#0f0a1e', text: '#fff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'linear', colors: ['#0f0a1e', '#1e1b4b', '#831843'], angle: 160 } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 6, keyframes: {}, visible: true, locked: false },
            { name: 'Color Block', type: 'shape', config: { shape: 'rect', fill: '#ec4899', width: 608, height: 200, rx: 20 }, x: 0, y: 500, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 6, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }], scaleX: [{ time: 0.5, value: 0, easing: 'spring' }, { time: 1.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'BIG NEWS', fontFamily: 'Inter', fontSize: 80, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true }, x: 304, y: 400, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.3, endTime: 6, keyframes: { opacity: [{ time: 0.3, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }], y: [{ time: 0.3, value: 350, easing: 'spring' }, { time: 1.5, value: 400, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Tap to learn more', fontFamily: 'Inter', fontSize: 28, fontWeight: '400', fill: '#ffffff', textAlign: 'center' }, x: 304, y: 590, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 6, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 2.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'cinematic-titles',
        name: 'Cinematic Titles',
        category: 'cinematic',
        description: 'Black background, massive Helvetica-style filmmaker title reveal.',
        aspectRatio: '16:9',
        duration: 10,
        tags: ['film', 'cinematic', 'dark', 'dramatic'],
        accent: '#ffffff',
        thumbnailGradient: ['#000000', '#111111'],
        thumbnailEmoji: '🎬',
        defaultText: { title: 'THE VISION', subtitle: 'A STORY BEGINS' },
        defaultColors: { primary: '#ffffff', bg: '#000000', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#000000' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: {}, visible: true, locked: false },
            { name: 'Top Bar', type: 'shape', config: { shape: 'rect', fill: '#000000', width: 1920, height: 100 }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: {}, visible: true, locked: false },
            { name: 'Bottom Bar', type: 'shape', config: { shape: 'rect', fill: '#000000', width: 1920, height: 100 }, x: 0, y: 980, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: {}, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'THE VISION', fontFamily: 'Inter', fontSize: 100, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 20 }, x: 960, y: 500, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 10, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeInOut' }, { time: 4, value: 1, easing: 'easeInOut' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'A STORY BEGINS', fontFamily: 'Inter', fontSize: 18, fontWeight: '300', fill: '#888888', textAlign: 'center', letterSpacing: 10 }, x: 960, y: 600, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 3, endTime: 10, keyframes: { opacity: [{ time: 3, value: 0, easing: 'easeInOut' }, { time: 5.5, value: 1, easing: 'easeInOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'gradient-flow',
        name: 'Gradient Flow',
        category: 'minimal',
        description: 'Animated gradient mesh background with a centered CTA.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['gradient', 'colorful', 'modern', 'cta'],
        accent: '#6366f1',
        thumbnailGradient: ['#6366f1', '#8b5cf6', '#ec4899'],
        thumbnailEmoji: '🌈',
        defaultText: { title: 'START TODAY', subtitle: 'Your journey begins here' },
        defaultColors: { primary: '#fff', bg1: '#6366f1', bg2: '#ec4899', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'animated', colors: ['#6366f1', '#8b5cf6', '#ec4899', '#f97316'], angle: 135, animationSpeed: 15 } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Vignette', type: 'overlay', config: { type: 'vignette', intensity: 0.3 }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'START TODAY', fontFamily: 'Inter', fontSize: 90, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 10 }, x: 960, y: 460, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], scaleX: [{ time: 0.5, value: 0.85, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }], scaleY: [{ time: 0.5, value: 0.85, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Your journey begins here', fontFamily: 'Inter', fontSize: 26, fontWeight: '400', fill: 'rgba(255,255,255,0.85)', textAlign: 'center' }, x: 960, y: 570, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'glitch-punk',
        name: 'Glitch Punk',
        category: 'trendy',
        description: 'RGB split glitch effect on text with distortion lines.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['glitch', 'punk', 'edgy', 'gaming', 'streetwear'],
        accent: '#00ff88',
        thumbnailGradient: ['#0a0a0a', '#1a0018'],
        thumbnailEmoji: '💥',
        defaultText: { title: 'DISRUPT', subtitle: 'Break The Rules' },
        defaultColors: { primary: '#00ff88', bg: '#0a0a0a', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#0a0a0a' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Glitch Overlay', type: 'overlay', config: { type: 'glitch' }, x: 0, y: 0, opacity: 0.7, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'DISRUPT', fontFamily: 'Inter', fontSize: 110, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, stroke: '#00ff88', strokeWidth: 2 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Break The Rules', fontFamily: 'Inter', fontSize: 24, fontWeight: '400', fill: '#00ff88', textAlign: 'center', glowColor: '#00ff88', glowRadius: 10, letterSpacing: 8 }, x: 960, y: 580, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 2.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'minimal-dot',
        name: 'Minimal Dot',
        category: 'minimal',
        description: 'White background, animated dot grid with clean sans-serif branding.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['minimal', 'clean', 'startup', 'modern'],
        accent: '#3b82f6',
        thumbnailGradient: ['#f8fafc', '#e2e8f0'],
        thumbnailEmoji: '⚪',
        defaultText: { title: 'Simple.', subtitle: 'Beautifully Effective' },
        defaultColors: { primary: '#3b82f6', bg: '#f8fafc', text: '#0f172a' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#f8fafc' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Particles', type: 'particle', config: { count: 40, color: ['#3b82f6', '#93c5fd', '#bfdbfe'], size: 4, speed: 0.5, spread: 800, lifetime: 4, shape: 'dot', gravity: 0, emitterX: 960, emitterY: 540 }, x: 0, y: 0, opacity: 0.4, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'Simple.', fontFamily: 'Inter', fontSize: 96, fontWeight: '800', fill: '#0f172a', textAlign: 'center' }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Beautifully Effective', fontFamily: 'Inter', fontSize: 26, fontWeight: '400', fill: '#3b82f6', textAlign: 'center', letterSpacing: 3 }, x: 960, y: 580, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'brand-splash',
        name: 'Brand Splash',
        category: 'corporate',
        description: 'Full-bleed brand color with animated concentric circles and logo pop.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['brand', 'splash', 'reveal', 'logo'],
        accent: '#f59e0b',
        thumbnailGradient: ['#7c3aed', '#4f46e5'],
        thumbnailEmoji: '🌟',
        defaultText: { title: 'BRAND NAME', subtitle: 'Your Tagline Here' },
        defaultColors: { primary: '#f59e0b', bg: '#4f46e5', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'radial', colors: ['#7c3aed', '#4f46e5', '#312e81'] } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Ring 1', type: 'shape', config: { shape: 'circle', fill: 'transparent', stroke: 'rgba(255,255,255,0.15)', strokeWidth: 2, width: 400, height: 400 }, x: 760, y: 340, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: { scaleX: [{ time: 0, value: 0.5, easing: 'easeOut' }, { time: 3, value: 1.5, easing: 'easeOut' }], scaleY: [{ time: 0, value: 0.5, easing: 'easeOut' }, { time: 3, value: 1.5, easing: 'easeOut' }], opacity: [{ time: 0, value: 0.8, easing: 'easeOut' }, { time: 3, value: 0, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Ring 2', type: 'shape', config: { shape: 'circle', fill: 'transparent', stroke: 'rgba(255,255,255,0.1)', strokeWidth: 2, width: 600, height: 600 }, x: 660, y: 240, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.3, endTime: 8, keyframes: { scaleX: [{ time: 0.3, value: 0.4, easing: 'easeOut' }, { time: 3.5, value: 1.5, easing: 'easeOut' }], scaleY: [{ time: 0.3, value: 0.4, easing: 'easeOut' }, { time: 3.5, value: 1.5, easing: 'easeOut' }], opacity: [{ time: 0.3, value: 0.6, easing: 'easeOut' }, { time: 3.5, value: 0, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'BRAND NAME', fontFamily: 'Inter', fontSize: 80, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 8 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }], scaleX: [{ time: 0.5, value: 0.7, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }], scaleY: [{ time: 0.5, value: 0.7, easing: 'spring' }, { time: 2, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Your Tagline Here', fontFamily: 'Inter', fontSize: 22, fontWeight: '400', fill: 'rgba(255,255,255,0.8)', textAlign: 'center', letterSpacing: 5 }, x: 960, y: 575, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'product-showcase',
        name: 'Product Showcase',
        category: 'corporate',
        description: 'Clean white with product image zoom and feature callouts.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['product', 'ecommerce', 'showcase', 'clean'],
        accent: '#10b981',
        thumbnailGradient: ['#f0fdf4', '#d1fae5'],
        thumbnailEmoji: '📦',
        defaultText: { title: 'PRODUCT NAME', subtitle: 'Premium Quality · Free Shipping · Guaranteed' },
        defaultColors: { primary: '#10b981', bg: '#ffffff', text: '#0f172a' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#ffffff' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Green Accent', type: 'shape', config: { shape: 'rect', fill: '#10b981', width: 8, height: 120 }, x: 260, y: 420, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.8, endTime: 8, keyframes: { opacity: [{ time: 0.8, value: 0, easing: 'easeOut' }, { time: 1.8, value: 1, easing: 'easeOut' }], scaleY: [{ time: 0.8, value: 0, easing: 'spring' }, { time: 1.8, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'PRODUCT NAME', fontFamily: 'Inter', fontSize: 64, fontWeight: '800', fill: '#0f172a', textAlign: 'left', uppercase: true, letterSpacing: 4 }, x: 300, y: 460, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], x: [{ time: 0.5, value: 260, easing: 'spring' }, { time: 2, value: 300, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Subtitle', type: 'text', config: { text: 'Premium Quality · Free Shipping · Guaranteed', fontFamily: 'Inter', fontSize: 18, fontWeight: '400', fill: '#64748b', textAlign: 'left' }, x: 300, y: 545, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1.5, endTime: 8, keyframes: { opacity: [{ time: 1.5, value: 0, easing: 'easeOut' }, { time: 3, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Price Badge', type: 'text', config: { text: 'FROM R99', fontFamily: 'Inter', fontSize: 32, fontWeight: '700', fill: '#10b981', textAlign: 'left', glowColor: '#10b981', glowRadius: 8 }, x: 300, y: 620, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 2.5, endTime: 8, keyframes: { opacity: [{ time: 2.5, value: 0, easing: 'easeOut' }, { time: 3.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'testimonial-quote',
        name: 'Testimonial Quote',
        category: 'corporate',
        description: 'Soft gradient with quote mark and auto-scrolling customer text.',
        aspectRatio: '16:9',
        duration: 10,
        tags: ['testimonial', 'review', 'trust', 'customer'],
        accent: '#8b5cf6',
        thumbnailGradient: ['#1e1b4b', '#312e81'],
        thumbnailEmoji: '💬',
        defaultText: { title: '"This product changed everything."', subtitle: '— Happy Customer, CEO of Company' },
        defaultColors: { primary: '#8b5cf6', bg: '#1e1b4b', text: '#e2e8f0' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'linear', colors: ['#1e1b4b', '#312e81', '#1e1b4b'], angle: 135 } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: {}, visible: true, locked: false },
            { name: 'Quote Mark', type: 'text', config: { text: '"', fontFamily: 'Playfair Display', fontSize: 200, fontWeight: '700', fill: 'rgba(139,92,246,0.3)', textAlign: 'center' }, x: 960, y: 420, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: { opacity: [{ time: 0, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Quote', type: 'text', config: { text: '"This product changed everything."', fontFamily: 'Inter', fontSize: 36, fontWeight: '600', fill: '#e2e8f0', textAlign: 'center' }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.8, endTime: 10, keyframes: { opacity: [{ time: 0.8, value: 0, easing: 'easeInOut' }, { time: 3, value: 1, easing: 'easeInOut' }] }, visible: true, locked: false },
            { name: 'Attribution', type: 'text', config: { text: '— Happy Customer, CEO of Company', fontFamily: 'Inter', fontSize: 20, fontWeight: '400', fill: '#8b5cf6', textAlign: 'center', letterSpacing: 2 }, x: 960, y: 565, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 2, endTime: 10, keyframes: { opacity: [{ time: 2, value: 0, easing: 'easeOut' }, { time: 4, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'countdown-blast',
        name: 'Countdown Blast',
        category: 'celebration',
        description: 'Animated countdown timer with particle confetti burst at zero.',
        aspectRatio: '16:9',
        duration: 10,
        tags: ['countdown', 'launch', 'event', 'excitement'],
        accent: '#fbbf24',
        thumbnailGradient: ['#7f1d1d', '#991b1b'],
        thumbnailEmoji: '🚀',
        defaultText: { title: 'LAUNCHING IN', subtitle: 'Get Ready!' },
        defaultColors: { primary: '#fbbf24', bg: '#1a0505', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'radial', colors: ['#2d1b00', '#1a0505', '#0a0a0a'] } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: {}, visible: true, locked: false },
            { name: 'Particles', type: 'particle', config: { count: 80, color: ['#fbbf24', '#f97316', '#ef4444', '#a855f7', '#3b82f6'], size: 5, speed: 4, spread: 600, lifetime: 2, shape: 'spark', gravity: 0.2, emitterX: 960, emitterY: 540 }, x: 0, y: 0, opacity: 0.8, rotation: 0, scaleX: 1, scaleY: 1, startTime: 7, endTime: 10, keyframes: { opacity: [{ time: 7, value: 0, easing: 'easeOut' }, { time: 8, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Launch Label', type: 'text', config: { text: 'LAUNCHING IN', fontFamily: 'Inter', fontSize: 32, fontWeight: '600', fill: '#fbbf24', textAlign: 'center', uppercase: true, letterSpacing: 8 }, x: 960, y: 380, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 10, keyframes: { opacity: [{ time: 0, value: 0, easing: 'easeOut' }, { time: 1, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Countdown', type: 'text', config: { text: '3', fontFamily: 'Inter', fontSize: 200, fontWeight: '900', fill: '#ffffff', textAlign: 'center', glowColor: '#fbbf24', glowRadius: 40 }, x: 960, y: 530, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 7, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Blast Text', type: 'text', config: { text: 'GET READY!', fontFamily: 'Inter', fontSize: 100, fontWeight: '900', fill: '#fbbf24', textAlign: 'center', uppercase: true, glowColor: '#fbbf24', glowRadius: 60 }, x: 960, y: 500, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 7.5, endTime: 10, keyframes: { opacity: [{ time: 7.5, value: 0, easing: 'spring' }, { time: 8.5, value: 1, easing: 'spring' }], scaleX: [{ time: 7.5, value: 0.5, easing: 'spring' }, { time: 8.5, value: 1, easing: 'spring' }], scaleY: [{ time: 7.5, value: 0.5, easing: 'spring' }, { time: 8.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'news-ticker',
        name: 'News Ticker',
        category: 'corporate',
        description: 'Horizontal scrolling headline bar with a BREAKING badge.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['news', 'broadcast', 'headline', 'ticker'],
        accent: '#ef4444',
        thumbnailGradient: ['#0f172a', '#1e293b'],
        thumbnailEmoji: '📰',
        defaultText: { title: 'BREAKING NEWS', subtitle: 'Latest updates from your industry right here' },
        defaultColors: { primary: '#ef4444', bg: '#0f172a', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'gradient', gradient: { type: 'linear', colors: ['#0f172a', '#1e293b'], angle: 135 } }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Red Bar', type: 'shape', config: { shape: 'rect', fill: '#ef4444', width: 1920, height: 70 }, x: 0, y: 440, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.5, endTime: 8, keyframes: { opacity: [{ time: 0.5, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }], scaleY: [{ time: 0.5, value: 0, easing: 'spring' }, { time: 1.5, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Breaking Badge', type: 'text', config: { text: '⚡ BREAKING', fontFamily: 'Inter', fontSize: 22, fontWeight: '900', fill: '#ffffff', textAlign: 'left', uppercase: true, letterSpacing: 2 }, x: 60, y: 475, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 8, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
            { name: 'Ticker Text', type: 'text', config: { text: 'Latest updates from your industry right here', fontFamily: 'Inter', fontSize: 22, fontWeight: '500', fill: '#ffffff', textAlign: 'left' }, x: 280, y: 475, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 1, endTime: 8, keyframes: { opacity: [{ time: 1, value: 0, easing: 'easeOut' }, { time: 2, value: 1, easing: 'easeOut' }], x: [{ time: 2, value: 280, easing: 'linear' }, { time: 8, value: -600, easing: 'linear' }] }, visible: true, locked: false },
            { name: 'Title', type: 'text', config: { text: 'BREAKING NEWS', fontFamily: 'Inter', fontSize: 72, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 8, glowColor: '#ef4444', glowRadius: 20 }, x: 960, y: 320, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: { opacity: [{ time: 0, value: 0, easing: 'easeOut' }, { time: 1.5, value: 1, easing: 'easeOut' }] }, visible: true, locked: false },
        ],
    },
    {
        id: 'kinetic-type',
        name: 'Kinetic Type',
        category: 'cinematic',
        description: 'High-impact words fly in with spring physics one after another.',
        aspectRatio: '16:9',
        duration: 8,
        tags: ['kinetic', 'typography', 'dynamic', 'motion'],
        accent: '#facc15',
        thumbnailGradient: ['#18181b', '#27272a'],
        thumbnailEmoji: '🔤',
        defaultText: { title: 'THINK BIG.', word1: 'MOVE', word2: 'FAST.', subtitle: 'Build the future.' },
        defaultColors: { primary: '#facc15', bg: '#18181b', text: '#ffffff' },
        layers: [
            { name: 'Background', type: 'background', config: { type: 'solid', fill: '#18181b' }, x: 0, y: 0, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0, endTime: 8, keyframes: {}, visible: true, locked: false },
            { name: 'Word 1', type: 'text', config: { text: 'THINK', fontFamily: 'Inter', fontSize: 100, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 10 }, x: 960, y: 400, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.3, endTime: 3, keyframes: { opacity: [{ time: 0.3, value: 0, easing: 'spring' }, { time: 1, value: 1, easing: 'spring' }, { time: 2.5, value: 1, easing: 'easeIn' }, { time: 3, value: 0, easing: 'easeIn' }], y: [{ time: 0.3, value: 500, easing: 'spring' }, { time: 1, value: 400, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Word 2', type: 'text', config: { text: 'BIG.', fontFamily: 'Inter', fontSize: 100, fontWeight: '900', fill: '#facc15', textAlign: 'center', uppercase: true, letterSpacing: 10, glowColor: '#facc15', glowRadius: 20 }, x: 960, y: 520, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 0.8, endTime: 3, keyframes: { opacity: [{ time: 0.8, value: 0, easing: 'spring' }, { time: 1.5, value: 1, easing: 'spring' }, { time: 2.5, value: 1, easing: 'easeIn' }, { time: 3, value: 0, easing: 'easeIn' }], x: [{ time: 0.8, value: 1200, easing: 'spring' }, { time: 1.5, value: 960, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Word 3', type: 'text', config: { text: 'MOVE FAST.', fontFamily: 'Inter', fontSize: 80, fontWeight: '900', fill: '#ffffff', textAlign: 'center', uppercase: true, letterSpacing: 6 }, x: 960, y: 460, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 3.2, endTime: 6, keyframes: { opacity: [{ time: 3.2, value: 0, easing: 'spring' }, { time: 4, value: 1, easing: 'spring' }, { time: 5.5, value: 1, easing: 'easeIn' }, { time: 6, value: 0, easing: 'easeIn' }], scaleX: [{ time: 3.2, value: 1.4, easing: 'spring' }, { time: 4, value: 1, easing: 'spring' }], scaleY: [{ time: 3.2, value: 1.4, easing: 'spring' }, { time: 4, value: 1, easing: 'spring' }] }, visible: true, locked: false },
            { name: 'Final Text', type: 'text', config: { text: 'Build the future.', fontFamily: 'Inter', fontSize: 52, fontWeight: '600', fill: '#facc15', textAlign: 'center', glowColor: '#facc15', glowRadius: 15 }, x: 960, y: 480, opacity: 1, rotation: 0, scaleX: 1, scaleY: 1, startTime: 6.2, endTime: 8, keyframes: { opacity: [{ time: 6.2, value: 0, easing: 'easeInOut' }, { time: 7.5, value: 1, easing: 'easeInOut' }] }, visible: true, locked: false },
        ],
    },
];
