export const FONTS = [
    // Sans Serif
    { name: 'Plus Jakarta Sans', value: '"Plus Jakarta Sans", sans-serif' },
    { name: 'Inter', value: '"Inter", sans-serif' },
    { name: 'Roboto', value: '"Roboto", sans-serif' },
    { name: 'Open Sans', value: '"Open Sans", sans-serif' },
    { name: 'Lato', value: '"Lato", sans-serif' },
    { name: 'Montserrat', value: '"Montserrat", sans-serif' },
    { name: 'Oswald', value: '"Oswald", sans-serif' },
    { name: 'Raleway', value: '"Raleway", sans-serif' },
    { name: 'Nunito', value: '"Nunito", sans-serif' },
    { name: 'Work Sans', value: '"Work Sans", sans-serif' },
    { name: 'Quicksand', value: '"Quicksand", sans-serif' },
    { name: 'Fira Sans', value: '"Fira Sans", sans-serif' },
    { name: 'Barlow', value: '"Barlow", sans-serif' },
    { name: 'Mulish', value: '"Mulish", sans-serif' },
    { name: 'Titillium Web', value: '"Titillium Web", sans-serif' },
    { name: 'Ubuntu', value: '"Ubuntu", sans-serif' },
    { name: 'Rubik', value: '"Rubik", sans-serif' },
    { name: 'Karla', value: '"Karla", sans-serif' },
    { name: 'DM Sans', value: '"DM Sans", sans-serif' },
    { name: 'Poppins', value: '"Poppins", sans-serif' },
    { name: 'Roboto Condensed', value: '"Roboto Condensed", sans-serif' },
    { name: 'Bebas Neue', value: '"Bebas Neue", sans-serif' },
    { name: 'Anton', value: '"Anton", sans-serif' },
    { name: 'Teko', value: '"Teko", sans-serif' },
    { name: 'Fjalla One', value: '"Fjalla One", sans-serif' },
    { name: 'Abel', value: '"Abel", sans-serif' },
    { name: 'Manrope', value: '"Manrope", sans-serif' },
    { name: 'Prompt', value: '"Prompt", sans-serif' },
    { name: 'Kanit', value: '"Kanit", sans-serif' },
    { name: 'Exo 2', value: '"Exo 2", sans-serif' },
    { name: 'Josefin Sans', value: '"Josefin Sans", sans-serif' },
    { name: 'Questrial', value: '"Questrial", sans-serif' },
    { name: 'Catamaran', value: '"Catamaran", sans-serif' },
    { name: 'Signika', value: '"Signika", sans-serif' },
    { name: 'Cuprum', value: '"Cuprum", sans-serif' },
    { name: 'Francois One', value: '"Francois One", sans-serif' },
    { name: 'Paytone One', value: '"Paytone One", sans-serif' },

    // Serif
    { name: 'Playfair Display', value: '"Playfair Display", serif' },
    { name: 'Merriweather', value: '"Merriweather", serif' },
    { name: 'Lora', value: '"Lora", serif' },
    { name: 'PT Serif', value: '"PT Serif", serif' },
    { name: 'Crimson Text', value: '"Crimson Text", serif' },
    { name: 'Libre Baskerville', value: '"Libre Baskerville", serif' },
    { name: 'Cormorant Garamond', value: '"Cormorant Garamond", serif' },
    { name: 'EB Garamond', value: '"EB Garamond", serif' },
    { name: 'Zilla Slab', value: '"Zilla Slab", serif' },
    { name: 'Bitter', value: '"Bitter", serif' },
    { name: 'Arvo', value: '"Arvo", serif' },
    { name: 'Rokkitt', value: '"Rokkitt", serif' },
    { name: 'Crete Round', value: '"Crete Round", serif' },
    { name: 'Bree Serif', value: '"Bree Serif", serif' },
    { name: 'Vollkorn', value: '"Vollkorn", serif' },
    { name: 'Abril Fatface', value: '"Abril Fatface", serif' },
    { name: 'Old Standard TT', value: '"Old Standard TT", serif' },
    { name: 'Cardo', value: '"Cardo", serif' },
    { name: 'Domine', value: '"Domine", serif' },
    { name: 'Spectral', value: '"Spectral", serif' },
    { name: 'Noticia Text', value: '"Noticia Text", serif' },
    { name: 'Glegoo', value: '"Glegoo", serif' },
    { name: 'Alice', value: '"Alice", serif' },
    { name: 'Amiri', value: '"Amiri", serif' },
    { name: 'Cinzel', value: '"Cinzel", serif' },
    { name: 'Frank Ruhl Libre', value: '"Frank Ruhl Libre", serif' },
    { name: 'Tinos', value: '"Tinos", serif' },

    // Display & Handwriting
    { name: 'Dancing Script', value: '"Dancing Script", cursive' },
    { name: 'Pacifico', value: '"Pacifico", cursive' },
    { name: 'Lobster', value: '"Lobster", cursive' },
    { name: 'Satisfy', value: '"Satisfy", cursive' },
    { name: 'Great Vibes', value: '"Great Vibes", cursive' },
    { name: 'Courgette', value: '"Courgette", cursive' },
    { name: 'Sacramento', value: '"Sacramento", cursive' },
    { name: 'Parisienne', value: '"Parisienne", cursive' },
    { name: 'Allura', value: '"Allura", cursive' },
    { name: 'Cookie', value: '"Cookie", cursive' },
    { name: 'Kaushan Script', value: '"Kaushan Script", cursive' },
    { name: 'Yellowtail', value: '"Yellowtail", cursive' },
    { name: 'Mr Dafoe', value: '"Mr Dafoe", cursive' },
    { name: 'Pinyon Script', value: '"Pinyon Script", cursive' },
    { name: 'Homemade Apple', value: '"Homemade Apple", cursive' },
    { name: 'Cedarville Cursive', value: '"Cedarville Cursive", cursive' },
    { name: 'La Belle Aurore', value: '"La Belle Aurore", cursive' },
    { name: 'Nothing You Could Do', value: '"Nothing You Could Do", cursive' },
    { name: 'Reenie Beanie', value: '"Reenie Beanie", cursive' },
    { name: 'Shadows Into Light', value: '"Shadows Into Light", cursive' },
    { name: 'Indie Flower', value: '"Indie Flower", cursive' },
    { name: 'Amatic SC', value: '"Amatic SC", cursive' },
    { name: 'Patrick Hand', value: '"Patrick Hand", cursive' },
    { name: 'Permanent Marker', value: '"Permanent Marker", cursive' },
    { name: 'Gloria Hallelujah', value: '"Gloria Hallelujah", cursive' },
    { name: 'Covered By Your Grace', value: '"Covered By Your Grace", cursive' },
    { name: 'Rock Salt', value: '"Rock Salt", cursive' },
    { name: 'Bangers', value: '"Bangers", cursive' },
    { name: 'Fredoka One', value: '"Fredoka One", cursive' },
    { name: 'Righteous', value: '"Righteous", cursive' },
    { name: 'Alfa Slab One', value: '"Alfa Slab One", cursive' },
    { name: 'Monoton', value: '"Monoton", cursive' },
    { name: 'Press Start 2P', value: '"Press Start 2P", cursive' },
    { name: 'Audiowide', value: '"Audiowide", cursive' },
    { name: 'Special Elite', value: '"Special Elite", cursive' },

    // Monospace
    { name: 'Roboto Mono', value: '"Roboto Mono", monospace' },
    { name: 'Inconsolata', value: '"Inconsolata", monospace' },
    { name: 'Source Code Pro', value: '"Source Code Pro", monospace' },
    { name: 'Space Mono', value: '"Space Mono", monospace' },
    { name: 'IBM Plex Mono', value: '"IBM Plex Mono", monospace' },
    { name: 'Ubuntu Mono', value: '"Ubuntu Mono", monospace' },
    { name: 'Anonymous Pro', value: '"Anonymous Pro", monospace' },
    { name: 'Cousine', value: '"Cousine", monospace' },
    { name: 'Fira Code', value: '"Fira Code", monospace' },
    { name: 'VT323', value: '"VT323", monospace' },
    { name: 'Cutive Mono', value: '"Cutive Mono", monospace' },
    { name: 'Nanum Gothic Coding', value: '"Nanum Gothic Coding", monospace' },
    { name: 'Oxygen Mono', value: '"Oxygen Mono", monospace' },
    { name: 'PT Mono', value: '"PT Mono", monospace' },
    { name: 'Share Tech Mono', value: '"Share Tech Mono", monospace' },
];

export const loadFonts = () => {
    const families = FONTS.map(f => f.value.split(',')[0].replace(/"/g, '').replace(/ /g, '+'));
    
    // Chunk requests to avoid URL length limits
    const chunkSize = 20;
    for (let i = 0; i < families.length; i += chunkSize) {
        const chunk = families.slice(i, i + chunkSize);
        const link = document.createElement('link');
        link.href = `https://fonts.googleapis.com/css2?family=${chunk.join('&family=')}&display=swap`;
        link.rel = 'stylesheet';
        document.head.appendChild(link);
    }
};
